# A

In [66]:
import numpy as np

## Разные функции создания

In [67]:
np.full([100, 100], 2)

array([[2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2],
       ...,
       [2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2]])

In [68]:
np.ones([100, 100])*2

array([[2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       ...,
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.]])

In [69]:
q = np.fromfunction(lambda i, j: j*i, (100, 100))

In [70]:
q.astype(str)

array([['0.0', '0.0', '0.0', ..., '0.0', '0.0', '0.0'],
       ['0.0', '1.0', '2.0', ..., '97.0', '98.0', '99.0'],
       ['0.0', '2.0', '4.0', ..., '194.0', '196.0', '198.0'],
       ...,
       ['0.0', '97.0', '194.0', ..., '9409.0', '9506.0', '9603.0'],
       ['0.0', '98.0', '196.0', ..., '9506.0', '9604.0', '9702.0'],
       ['0.0', '99.0', '198.0', ..., '9603.0', '9702.0', '9801.0']],
      dtype='<U32')

In [71]:
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64],
 'complex': [numpy.complex64, numpy.complex128],
 'others': [bool, object, bytes, str, numpy.void]}

## Доступы к элементам

In [72]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
a = np.array([[1, 2], [5, 6]])
print(a[1, 1])
print(a[0, 1])
print(a[1, 0])
print(a[0, 0])

6
2
5
1


## Слайсы и срезы

In [74]:
a = np.arange(10)
print(a[1:8:1])
print(a[1:8:2])
print(a[1:8:3])
print(a[1:30:1])

[1 2 3 4 5 6 7]
[1 3 5 7]
[1 4 7]
[1 2 3 4 5 6 7 8 9]


In [75]:
a = np.array([ [1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
a[0] #тоже самое что и
a[0,:]

array([1, 2, 3])

In [77]:
a[1:3, 0:2]

array([[4, 5],
       [7, 8]])

In [78]:
# a[from:to:step, from:to:step, from:to:step ...]

numpy слайсами не копируют массивы и не меняют их, они меняют их отображение\представление

### Форма масива и ее изменение

In [79]:
a = np.arange(36)
a.shape

(36,)

In [80]:
a.reshape(6, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [81]:
a.reshape(2, -1) # тогда на месте -1 будеь вычесленно значение самостоятельно в данном случае это 18

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35]])

In [82]:
a.ravel() # развертывает в 1 мерный массив

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

## Математические операции

Мат операции очевидно те же что и в обычном, однако для произведения векторов и матриц идут исключения:

In [85]:
A = np.arange(10)
B = np.arange(10)

A*B

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Формы массивов не обязательно должны совпадать, главное что бы они были broadcast

In [90]:
a = np.array([[1, 2, 3], [2, 3, 4]])
b = np.array([3, 4, 5])
c = np.array([1, 2])
print(a+b)
# print(a + c) но это не работает

[[4 6 8]
 [5 7 9]]


In [91]:
a = np.eye(10, 10)
b = np.arange(10)
a*b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 4., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 5., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 6., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 7., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 9.]])

In [94]:
N = 10
a = np.eye(N, N)
b = np.arange(1, N + 1)[::-1]
a*b**2

array([[100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  81.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,  64.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  49.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,  36.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,  25.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,  16.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   9.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   4.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.]])

In [120]:
# @ матричное умножение

A = np.array([1, 2, 3])
M = np.eye(3, 3)
M = M[:1,:2]
print(M)

[[1. 0.]]


In [152]:
a = np.ones([3, 2, 2])
b = np.ones([3, 2, 2])
(a@b).shape

(3, 3, 3)